In [89]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt

# Preparación del Dataset: Tratamiento y Limpieza Inicial

In [90]:

df = pd.read_parquet('../data/interim/fide_players_bruto.parquet')
print(df.info())
df.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 1914517 entries, 0 to 1914516
Data columns (total 12 columns):
 #   Column        Dtype
---  ------        -----
 0   fideid        int64
 1   name          str
 2   country       str
 3   sex           str
 4   title         str
 5   w_title       str
 6   o_title       str
 7   rating        int64
 8   rapid_rating  int64
 9   blitz_rating  int64
 10  birthday      float64
 11  flag          str
dtypes: float64(1), int64(4), str(7)
memory usage: 216.3 MB
None

,fideid,name,country,sex,title,w_title,o_title,rating,rapid_rating,blitz_rating,birthday,flag
0,10292519,"A A M Imtiaz, Chowdhury",BAN,M,NaN,NaN,NaN,0,0,0,1975.0,NaN
1,10688862,"A Abdel Maabod, Hoda",EGY,F,NaN,NaN,NaN,0,0,0,2009.0,w
2,577017641,A Adhisiva,IND,M,NaN,NaN,NaN,0,0,0,2015.0,NaN
3,577038320,A Akilesh Kumar,IND,M,NaN,NaN,NaN,0,0,0,2015.0,NaN
4,33496722,A Aman,IND,M,NaN,NaN,NaN,0,0,0,1996.0,NaN
5,577037219,A Anuj,IND,M,NaN,NaN,NaN,0,0,0,2015.0,NaN
6,537001345,A Arbhin Vanniarajan,IND,M,NaN,NaN,NaN,1450,1500,1431,2018.0,NaN
7,35853913,"A Aziz, Mohd Azizi Jamil",MAS,M,NaN,NaN,NaN,0,0,0,1981.0,NaN
8,35893303,"A Aziz, Mohd Khalis",MAS,M,NaN,NaN,NaN,0,0,0,1991.0,NaN
9,10224084,"A B M Hasibuzzaman, Tapan",BAN,M,NaN,NaN,NaN,0,0,0,1977.0,NaN

In [91]:
columnas_titulos = ['title','w_title',"o_title"]

for col in columnas_titulos:
    df[col] = df[col].fillna('nt')

df['flag'] = df['flag'].fillna('a')

In [92]:
variables_numericas = [
    'rating',
    'rapid_rating',
    'blitz_rating', 
    'birthday'
]

variables_categoricas = [
    'sex',
    'country',
    'flag',
    'w_title',
    'title',
    'o_title'
]   

for var in variables_numericas:
  df[var] = pd.to_numeric(df[var], errors="coerce").astype("Int64")

for col in variables_categoricas:
  df[col] = df[col].astype("category")

df['fideid'] = df['fideid'].astype('string')
df['name'] = df['name'].astype('string')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1914517 entries, 0 to 1914516
Data columns (total 12 columns):
 #   Column        Dtype
---  ------        -----
 0   fideid        string
 1   name          string
 2   country       category
 3   sex           category
 4   title         category
 5   w_title       category
 6   o_title       category
 7   rating        Int64
 8   rapid_rating  Int64
 9   blitz_rating  Int64
 10  birthday      Int64
 11  flag          category
dtypes: Int64(4), category(6), string(2)
memory usage: 156.0 MB

In [93]:
df_limpio = df[
    (df['rating'] > 0) | 
    (df['rapid_rating'] > 0) | 
    (df['blitz_rating'] > 0)
]

df_limpio = df_limpio.dropna(subset=['birthday'])


df_limpio.info()

<class 'pandas.DataFrame'>
Index: 776189 entries, 6 to 1914511
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   fideid        776189 non-null  string
 1   name          776189 non-null  string
 2   country       776189 non-null  category
 3   sex           776189 non-null  category
 4   title         776189 non-null  category
 5   w_title       776189 non-null  category
 6   o_title       776189 non-null  category
 7   rating        776189 non-null  Int64
 8   rapid_rating  776189 non-null  Int64
 9   blitz_rating  776189 non-null  Int64
 10  birthday      776189 non-null  Int64
 11  flag          776189 non-null  category
dtypes: Int64(4), category(6), string(2)
memory usage: 69.1 MB

In [94]:
columnas_titulos = ['title','w_title',"o_title"]

for col in columnas_titulos:
    df_limpio[col] = df_limpio[col].fillna('nt')

In [95]:
duplicados_id = df_limpio.duplicated(subset=['fideid']).sum()
print(f"Cantidad de registros con FIDE ID repetido: {duplicados_id}")

if duplicados_id > 0:
    filas_repetidas = df_limpio[df_limpio.duplicated(subset=['fideid'], keep=False)]
    display(filas_repetidas)

Cantidad de registros con FIDE ID repetido: 1

,fideid,name,country,sex,title,w_title,o_title,rating,rapid_rating,blitz_rating,birthday,flag
1645645,5019168,Sridharan Ramanathan,IND,M,nt,nt,nt,1841,1702,1782,1965,i
1645646,5019168,Sridharan Ramanathan,IND,M,nt,nt,nt,1841,1702,1782,1965,i

In [96]:
df_limpio.head()

,fideid,name,country,sex,title,w_title,o_title,rating,rapid_rating,blitz_rating,birthday,flag
6,537001345,A Arbhin Vanniarajan,IND,M,nt,nt,nt,1450,1500,1431,2018,a
10,10245154,"A B M Jobair, Hossain",BAN,M,nt,nt,nt,1715,1738,1748,1998,a
15,558074015,A Bala Phani Prabhanjan,IND,M,nt,nt,nt,1585,1553,1524,2012,a
17,12457558,A Bu Ba Co,VIE,M,nt,nt,nt,0,1638,0,2002,a
18,25121731,A C J John,IND,M,nt,nt,nt,1438,0,0,1987,i

In [97]:
df_flag = df_limpio['flag'].value_counts().reset_index()
df_flag

  flag   count
0    a  395058
1    i  300294
2    w   42198
3   wi   38639

In [98]:
df_limpio['es_activo'] = ~df_limpio['flag'].isin(['i', 'wi'])

df_limpio.info()

<class 'pandas.DataFrame'>
Index: 776189 entries, 6 to 1914511
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   fideid        776189 non-null  string
 1   name          776189 non-null  string
 2   country       776189 non-null  category
 3   sex           776189 non-null  category
 4   title         776189 non-null  category
 5   w_title       776189 non-null  category
 6   o_title       776189 non-null  category
 7   rating        776189 non-null  Int64
 8   rapid_rating  776189 non-null  Int64
 9   blitz_rating  776189 non-null  Int64
 10  birthday      776189 non-null  Int64
 11  flag          776189 non-null  category
 12  es_activo     776189 non-null  bool
dtypes: Int64(4), bool(1), category(6), string(2)
memory usage: 69.9 MB

In [99]:
df_limpio.describe()

            rating  rapid_rating  blitz_rating     birthday
count     776189.0      776189.0      776189.0     776189.0
mean   1249.219447   1014.549386    690.320292  1990.935498
std     802.649663    834.810625     854.07447    20.410485
min            0.0           0.0           0.0         15.0
25%            0.0           0.0           0.0       1977.0
50%         1588.0        1482.0           0.0       1997.0
75%         1808.0        1685.0        1617.0       2008.0
max         2823.0        2803.0        2860.0       2022.0

In [100]:
errores_nacimiento = df_limpio[df_limpio['birthday'] < 1920]
df_limpio = df_limpio[df_limpio['birthday'] >= 1920].copy()
print(f"Registros con año de nacimiento ilógico: {len(errores_nacimiento)}")

Registros con año de nacimiento ilógico: 1

In [101]:
fecha = dt.datetime.now()
df_limpio['edad'] = fecha.year - df_limpio['birthday']

In [102]:
df_limpio.describe()

            rating  rapid_rating  blitz_rating     birthday       edad
count     776188.0      776188.0      776188.0     776188.0   776188.0
mean   1249.219152   1014.550693    690.321181  1990.938043  35.061957
std     802.650138    834.810368    854.074661    20.286899  20.286899
min            0.0           0.0           0.0       1920.0        4.0
25%            0.0           0.0           0.0       1977.0       18.0
50%         1588.0        1482.0           0.0       1997.0       29.0
75%         1808.0        1685.0        1617.0       2008.0       49.0
max         2823.0        2803.0        2860.0       2022.0      106.0

In [103]:
jugador_centenario = df_limpio[df_limpio['birthday'] == 1920]
display(jugador_centenario)

,fideid,name,country,sex,title,w_title,o_title,rating,rapid_rating,blitz_rating,birthday,flag,es_activo,edad
307804,105864,"Carames, Luis",ARG,M,nt,nt,nt,2040,0,0,1920,i,False,106
365304,24515850,"Codina Espinasa, Joan",ESP,M,nt,nt,nt,1695,0,0,1920,i,False,106
464602,2004739,"Donnelly, Ruth",USA,F,nt,nt,nt,2030,0,0,1920,wi,False,106
726783,611514,"Huguet, Marcel",FRA,M,nt,nt,nt,1550,0,0,1920,i,False,106
858331,24114065,"Kinin, Igor",RUS,M,nt,nt,nt,2013,1995,1948,1920,i,False,106
869861,24635049,"Koch, Horst",GER,M,nt,nt,nt,1847,0,0,1920,i,False,106
896473,24114081,"Kramorev, Yuri",RUS,M,nt,nt,nt,1975,0,0,1920,i,False,106
921349,4134028,"Kuznetsov, Fiodor",RUS,M,nt,nt,nt,1947,0,0,1920,i,False,106
949148,22718273,"Lederman, Isaac",BRA,M,nt,nt,nt,0,1627,0,1920,a,True,106
1178342,340219,"Muzik, Ferdinand",CZE,M,nt,nt,nt,1743,0,0,1920,i,False,106
1182311,4631560,"Nadenau, Oskar",GER,M,nt,nt,nt,1982,0,0,1920,i,False,106
1726641,4645987,"Tochtermann, Georg, Dr.",GER,M,nt,nt,nt,1951,0,0,1920,i,False,106
1865283,2801752,"Yaroslavsky, Michael",ISR,M,nt,nt,nt,1807,0,0,1920,i,False,106

In [104]:

df_activos = df_limpio[~df_limpio['flag'].isin(['i', 'wi'])].copy()
df_activos = df_activos[df_activos['edad'] <= 95].copy()

df_activos.describe()

           rating  rapid_rating  blitz_rating     birthday       edad
count    437166.0      437166.0      437166.0     437166.0   437166.0
mean   870.435578   1230.279063    791.654141  1994.075658  31.924342
std    881.505245    745.092034    862.417965    19.752039  19.752039
min           0.0           0.0           0.0       1931.0        4.0
25%           0.0           0.0           0.0       1980.0       16.0
50%        1404.0        1531.0           0.0       2001.0       25.0
75%        1701.0        1705.0        1642.0       2010.0       46.0
max        2823.0        2803.0        2860.0       2022.0       95.0

In [105]:
df_activos.info()

<class 'pandas.DataFrame'>
Index: 437166 entries, 6 to 1914511
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   fideid        437166 non-null  string
 1   name          437166 non-null  string
 2   country       437166 non-null  category
 3   sex           437166 non-null  category
 4   title         437166 non-null  category
 5   w_title       437166 non-null  category
 6   o_title       437166 non-null  category
 7   rating        437166 non-null  Int64
 8   rapid_rating  437166 non-null  Int64
 9   blitz_rating  437166 non-null  Int64
 10  birthday      437166 non-null  Int64
 11  flag          437166 non-null  category
 12  es_activo     437166 non-null  bool
 13  edad          437166 non-null  Int64
dtypes: Int64(5), bool(1), category(6), string(2)
memory usage: 43.2 MB

In [106]:
df_limpio.to_parquet('../data/processed/fide_players_all.parquet', index=False)

df_activos.to_parquet('../data/processed/fide_players_active.parquet', index=False)

print(f"   - Todos los jugadores: {len(df_limpio)} registros guardados en 'fide_players_all.parquet'")
print(f"   - Jugadores activos: {len(df_activos)} registros guardados en 'fide_players_active.parquet'")

   - Todos los jugadores: 776188 registros guardados en 'fide_players_all.parquet'
   - Jugadores activos: 437166 registros guardados en 'fide_players_active.parquet'