# Preparación del Dataset: Tratamiento y Limpieza Inicial

Pipeline de limpieza del padrón oficial FIDE (~1.9M registros) para generar dos datasets curados.

## Índice

1. [Carga de Datos Brutos](#1-carga-de-datos-brutos)
2. [Tratamiento de Valores Nulos](#2-tratamiento-de-valores-nulos)
3. [Tipado y Optimización de Memoria](#3-tipado-y-optimización-de-memoria)
4. [Filtrado de Registros Válidos](#4-filtrado-de-registros-válidos)
5. [Control de Duplicados](#5-control-de-duplicados)
6. [Análisis de Flags de Actividad](#6-análisis-de-flags-de-actividad)
7. [Estadísticos Descriptivos Iniciales](#7-estadísticos-descriptivos-iniciales)
8. [Depuración de Año de Nacimiento](#8-depuración-de-año-de-nacimiento)
9. [Ingeniería de Variables: Edad y Categorías](#9-ingeniería-de-variables-edad-y-categorías)
10. [Segmentación de Jugadores Activos](#10-segmentación-de-jugadores-activos)
11. [Exportación de Datasets Procesados](#11-exportación-de-datasets-procesados)

In [486]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt

## 1. Carga de Datos Brutos

Se carga el archivo `fide_players_bruto.parquet` generado por el pipeline de ingesta streaming.
Contiene ~1.9M de registros del padrón mundial FIDE sin filtros.

In [487]:
from src.config.settings import DATA_INTERIM_DIR
from src.utils.snapshot import latest_snapshot, interim_path

SNAPSHOT = latest_snapshot(DATA_INTERIM_DIR)
df = pd.read_parquet(interim_path(SNAPSHOT))
print(df.info())
df.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 1933950 entries, 0 to 1933949
Data columns (total 13 columns):
 #   Column         Dtype
---  ------         -----
 0   fideid         int64
 1   name           str
 2   country        str
 3   sex            str
 4   title          str
 5   w_title        str
 6   o_title        str
 7   rating         int64
 8   rapid_rating   int64
 9   blitz_rating   int64
 10  birthday       float64
 11  flag           str
 12  snapshot_date  object
dtypes: float64(1), int64(4), object(1), str(7)
memory usage: 233.2+ MB
None

,fideid,name,country,sex,title,w_title,o_title,rating,rapid_rating,blitz_rating,birthday,flag,snapshot_date
0,10292519,"A A M Imtiaz, Chowdhury",BAN,M,NaN,NaN,NaN,0,0,0,1975.0,NaN,2026-10-01
1,10688862,"A Abdel Maabod, Hoda",EGY,F,NaN,NaN,NaN,0,0,0,2009.0,w,2026-10-01
2,577017641,A Adhisiva,IND,M,NaN,NaN,NaN,0,0,0,2015.0,NaN,2026-10-01
3,577038320,A Akilesh Kumar,IND,M,NaN,NaN,NaN,0,0,0,2015.0,NaN,2026-10-01
4,33496722,A Aman,IND,M,NaN,NaN,NaN,0,0,0,1996.0,NaN,2026-10-01
5,577037219,A Anuj,IND,M,NaN,NaN,NaN,0,0,0,2015.0,NaN,2026-10-01
6,537001345,A Arbhin Vanniarajan,IND,M,NaN,NaN,NaN,1450,1475,1431,2018.0,NaN,2026-10-01
7,35853913,"A Aziz, Mohd Azizi Jamil",MAS,M,NaN,NaN,NaN,0,0,0,1981.0,NaN,2026-10-01
8,35893303,"A Aziz, Mohd Khalis",MAS,M,NaN,NaN,NaN,0,0,0,1991.0,NaN,2026-10-01
9,10224084,"A B M Hasibuzzaman, Tapan",BAN,M,NaN,NaN,NaN,0,0,0,1977.0,NaN,2026-10-01

## 2. Tratamiento de Valores Nulos

- **Títulos** (`title`, `w_title`, `o_title`): Los valores `NaN` se imputan como `'nt'` (no title).
- **Flag de actividad** (`flag`): Los valores `NaN` se imputan como `'a'` (activo).

In [488]:
columnas_titulos = ['title','w_title',"o_title"]

for col in columnas_titulos:
    df[col] = df[col].fillna('nt')

df['flag'] = df['flag'].fillna('a')

## 3. Tipado y Optimización de Memoria

Conversión de tipos para optimizar el uso de memoria:
- Variables numéricas (`rating`, `rapid_rating`, `blitz_rating`, `birthday`) → `Int64`
- Variables categóricas (`sex`, `country`, `flag`, títulos) → `category`
- Identificadores (`fideid`, `name`) → `string`

In [489]:
variables_numericas = [
    'rating',
    'rapid_rating',
    'blitz_rating', 
    'birthday'
]

variables_categoricas = [
    'sex',
    'country',
    'flag',
    'w_title',
    'title',
    'o_title'
]   

for var in variables_numericas:
  df[var] = pd.to_numeric(df[var], errors="coerce").astype("Int64")

for col in variables_categoricas:
  df[col] = df[col].astype("category")

df['fideid'] = df['fideid'].astype('string')
df['name'] = df['name'].astype('string')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1933950 entries, 0 to 1933949
Data columns (total 13 columns):
 #   Column         Dtype
---  ------         -----
 0   fideid         string
 1   name           string
 2   country        category
 3   sex            category
 4   title          category
 5   w_title        category
 6   o_title        category
 7   rating         Int64
 8   rapid_rating   Int64
 9   blitz_rating   Int64
 10  birthday       Int64
 11  flag           category
 12  snapshot_date  object
dtypes: Int64(4), category(6), object(1), string(2)
memory usage: 172.3+ MB

$$GM>IM>WGM>FM>WIM>CM>WFM>WCM>nt$$

In [490]:
print(df['title'].value_counts())
print(df['w_title'].value_counts())

title
nt     1909048
FM        9852
IM        4308
CM        3913
WFM       2240
GM        1900
WCM       1405
WIM        941
WGM        343
Name: count, dtype: int64
w_title
nt     1928756
WFM       2265
WCM       1408
WIM        982
WGM        539
Name: count, dtype: int64

## 4. Filtrado de Registros Válidos

Criterios de filtrado:
- Retener solo jugadores con **al menos un rating > 0** (clásico, rápido o blitz).
- Reemplazar los ratings con valor 0 por `NaN` (indican ausencia de dato, no rating real).
- Eliminar registros sin año de nacimiento (`birthday`).

> Esto descarta ~1.1M de registros con Elo cero (jugadores escolares, árbitros, registros administrativos).

In [491]:
df_limpio = df[
    (df['rating'] > 0) | 
    (df['rapid_rating'] > 0) | 
    (df['blitz_rating'] > 0)
]

df_limpio = df_limpio.replace(0, np.nan)

df_limpio = df_limpio.dropna(subset=['birthday'])


df_limpio.info()

<class 'pandas.DataFrame'>
Index: 782834 entries, 6 to 1933944
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   fideid         782834 non-null  string
 1   name           782834 non-null  string
 2   country        782834 non-null  category
 3   sex            782834 non-null  category
 4   title          782834 non-null  category
 5   w_title        782834 non-null  category
 6   o_title        782834 non-null  category
 7   rating         561191 non-null  Int64
 8   rapid_rating   475831 non-null  Int64
 9   blitz_rating   314804 non-null  Int64
 10  birthday       782834 non-null  Int64
 11  flag           782834 non-null  category
 12  snapshot_date  782834 non-null  object
dtypes: Int64(4), category(6), object(1), string(2)
memory usage: 75.7+ MB

Re-imputación de títulos tras el filtrado para asegurar consistencia.

In [492]:
columnas_titulos = ['title','w_title',"o_title"]

for col in columnas_titulos:
    df_limpio[col] = df_limpio[col].fillna('nt')

In [493]:
sin_espacios = df_limpio["title"].str.strip()
print((df_limpio["title"] != sin_espacios).sum())

0

In [494]:
for valor in df_limpio["title"].dropna().unique():
    print(repr(valor))

'nt'
'IM'
'WCM'
'FM'
'WFM'
'GM'
'WIM'
'CM'
'WGM'

In [495]:
for valor in df_limpio["w_title"].dropna().unique():
    print(repr(valor))

'nt'
'WCM'
'WFM'
'WIM'
'WGM'

In [496]:



titulos_orden = ["GM", "IM", "WGM", "FM", "WIM", "CM", "WFM", "WCM"]
orden = ["nt"] + titulos_orden[::-1]

t = pd.Categorical(df_limpio["title"], categories=orden, ordered=True)
w = pd.Categorical(df_limpio["w_title"], categories=orden, ordered=True)

codigos = np.maximum(t.codes, w.codes)
df_limpio["title"] = pd.Categorical.from_codes(codigos, categories=orden, ordered=True)
df_limpio = df_limpio.drop(columns="w_title")

print(df_limpio["title"].value_counts())

print(df_limpio["title"].value_counts().sum())

title
nt     758138
FM       9755
IM       4294
CM       3861
WFM      2225
GM       1900
WCM      1364
WIM       935
WGM       362
Name: count, dtype: int64
782834

## 5. Control de Duplicados

Verificación de unicidad por `fideid`. Se espera que cada jugador tenga un ID FIDE único.

In [497]:
duplicados_id = df_limpio.duplicated(subset=['fideid']).sum()
print(f"Cantidad de registros con FIDE ID repetido: {duplicados_id}")

if duplicados_id > 0:
    filas_repetidas = df_limpio[df_limpio.duplicated(subset=['fideid'], keep=False)]
    display(filas_repetidas)

Cantidad de registros con FIDE ID repetido: 0

Verificación visual del dataset tras limpieza y deduplicación.

In [498]:
df_limpio.head()

,fideid,name,country,sex,title,o_title,rating,rapid_rating,blitz_rating,birthday,flag,snapshot_date
6,537001345,A Arbhin Vanniarajan,IND,M,nt,nt,1450,1475,1431,2018,a,2026-10-01
10,10245154,"A B M Jobair, Hossain",BAN,M,nt,nt,1715,1738,1748,1998,a,2026-10-01
17,558074015,A Bala Phani Prabhanjan,IND,M,nt,nt,1585,1553,1524,2012,a,2026-10-01
19,12457558,A Bu Ba Co,VIE,M,nt,nt,<NA>,1638,<NA>,2002,a,2026-10-01
20,25121731,A C J John,IND,M,nt,nt,1438,<NA>,<NA>,1987,i,2026-10-01

## 6. Análisis de Flags de Actividad

Los flags de la FIDE indican el estado del jugador:
- `a` → Activo
- `i` → Inactivo
- `w` → Mujer activa
- `wi` → Mujer inactiva

Se crea la variable booleana `es_activo` derivada de estos flags.

In [499]:
df_flag = df_limpio['flag'].value_counts().reset_index()
df_flag

  flag   count
0    a  399342
1    i  301942
2    w   42652
3   wi   38898

In [500]:
df_limpio['es_activo'] = ~df_limpio['flag'].isin(['i', 'wi'])

df_limpio.info()

<class 'pandas.DataFrame'>
Index: 782834 entries, 6 to 1933944
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   fideid         782834 non-null  string
 1   name           782834 non-null  string
 2   country        782834 non-null  category
 3   sex            782834 non-null  category
 4   title          782834 non-null  category
 5   o_title        782834 non-null  category
 6   rating         561191 non-null  Int64
 7   rapid_rating   475831 non-null  Int64
 8   blitz_rating   314804 non-null  Int64
 9   birthday       782834 non-null  Int64
 10  flag           782834 non-null  category
 11  snapshot_date  782834 non-null  object
 12  es_activo      782834 non-null  bool
dtypes: Int64(4), bool(1), category(5), object(1), string(2)
memory usage: 75.7+ MB

## 7. Estadísticos Descriptivos Iniciales

Resumen estadístico del dataset filtrado para validar rangos y detectar anomalías.

In [501]:
df_limpio.describe()

            rating  rapid_rating  blitz_rating     birthday
count     561191.0      475831.0      314804.0     782834.0
mean   1735.963549   1675.841952   1719.251655  1991.039242
std     221.964757    203.641774    214.732628     20.40581
min         1400.0        1400.0        1400.0         15.0
25%         1556.0        1514.0        1548.0       1977.0
50%         1706.0        1634.0        1686.0       1998.0
75%         1880.0        1797.0        1854.0       2008.0
max         2823.0        2801.0        2860.0       2022.0

## 8. Depuración de Año de Nacimiento

Eliminación de registros con `birthday < 1920` como valores ilógicos o errores de registro.

In [502]:
errores_nacimiento = df_limpio[df_limpio['birthday'] < 1920]
df_limpio = df_limpio[df_limpio['birthday'] >= 1920].copy()
print(f"Registros con año de nacimiento ilógico: {len(errores_nacimiento)}")

Registros con año de nacimiento ilógico: 1

## 9. Ingeniería de Variables: Edad y Categorías

### 9.1. Cálculo de Edad
Variable derivada: `edad = año_actual - birthday`.

In [503]:
fecha = dt.datetime.now()
df_limpio['edad'] = fecha.year - df_limpio['birthday']

Estadísticos descriptivos tras incorporar la variable `edad`.

In [504]:
df_limpio.describe()

            rating  rapid_rating  blitz_rating     birthday       edad
count     561190.0      475830.0      314804.0     782833.0   782833.0
mean   1735.964009   1675.842519   1719.251655  1991.041766  34.958234
std     221.964688    203.641613    214.732628    20.283235  20.283235
min         1400.0        1400.0        1400.0       1920.0        4.0
25%         1556.0        1514.0        1548.0       1977.0       18.0
50%         1706.0        1634.0        1686.0       1998.0       28.0
75%         1880.0        1797.0        1854.0       2008.0       49.0
max         2823.0        2801.0        2860.0       2022.0      106.0

### 9.2. Inspección de Jugadores Centenarios

Revisión de jugadores nacidos en 1920 (los más antiguos del dataset tras el filtro).

In [505]:
jugador_centenario = df_limpio[df_limpio['birthday'] == 1920]
display(jugador_centenario)

,fideid,name,country,sex,title,o_title,rating,rapid_rating,blitz_rating,birthday,flag,snapshot_date,es_activo,edad
311061,105864,"Carames, Luis",ARG,M,nt,nt,2040,<NA>,<NA>,1920,i,2026-10-01,False,106
369102,24515850,"Codina Espinasa, Joan",ESP,M,nt,nt,1695,<NA>,<NA>,1920,i,2026-10-01,False,106
469447,2004739,"Donnelly, Ruth",USA,F,nt,nt,2030,<NA>,<NA>,1920,wi,2026-10-01,False,106
734112,611514,"Huguet, Marcel",FRA,M,nt,nt,1550,<NA>,<NA>,1920,i,2026-10-01,False,106
867040,24114065,"Kinin, Igor",RUS,M,nt,nt,2013,1995,1948,1920,i,2026-10-01,False,106
878655,24635049,"Koch, Horst",GER,M,nt,nt,1847,<NA>,<NA>,1920,i,2026-10-01,False,106
905473,24114081,"Kramorev, Yuri",RUS,M,nt,nt,1975,<NA>,<NA>,1920,i,2026-10-01,False,106
930562,4134028,"Kuznetsov, Fiodor",RUS,M,nt,nt,1947,<NA>,<NA>,1920,i,2026-10-01,False,106
958621,22718273,"Lederman, Isaac",BRA,M,nt,nt,<NA>,1627,<NA>,1920,a,2026-10-01,True,106
1190359,340219,"Muzik, Ferdinand",CZE,M,nt,nt,1743,<NA>,<NA>,1920,i,2026-10-01,False,106
1194375,4631560,"Nadenau, Oskar",GER,M,nt,nt,1982,<NA>,<NA>,1920,i,2026-10-01,False,106
1744185,4645987,"Tochtermann, Georg, Dr.",GER,M,nt,nt,1951,<NA>,<NA>,1920,i,2026-10-01,False,106
1884213,2801752,"Yaroslavsky, Michael",ISR,M,nt,nt,1807,<NA>,<NA>,1920,i,2026-10-01,False,106

### 9.3. Creación de Categorías por Edad

Clasificación en categorías oficiales de ajedrez juvenil:

| Categoría | Rango de Edad |
| :--- | :--- |
| Sub 8 | 0 – 7 años |
| Sub 10 | 8 – 9 años |
| Sub 12 | 10 – 11 años |
| Sub 14 | 12 – 13 años |
| Sub 16 | 14 – 15 años |
| Sub 18 | 16 – 17 años |
| Sub 20 | 18 – 19 años |
| Absoluta | 20+ años |

In [506]:
orden_jerarquico = [
    "Sub 8", "Sub 10", "Sub 12", "Sub 14", 
    "Sub 16", "Sub 18", "Sub 20", "Absoluta"
]

reglas_ajedrez = {
    "Sub 8":  (df_limpio["edad"] > 0) & (df_limpio["edad"] < 8),
    "Sub 10": (df_limpio["edad"] >= 8) & (df_limpio["edad"] < 10),
    "Sub 12": (df_limpio["edad"] >= 10) & (df_limpio["edad"] < 12),
    "Sub 14": (df_limpio["edad"] >= 12) & (df_limpio["edad"] < 14),
    "Sub 16": (df_limpio["edad"] >= 14) & (df_limpio["edad"] < 16),
    "Sub 18": (df_limpio["edad"] >= 16) & (df_limpio["edad"] < 18),
    "Sub 20": (df_limpio["edad"] >= 18) & (df_limpio["edad"] < 20),
    "Absoluta": df_limpio["edad"] >= 20,
}

df_limpio["categoria"] = np.select(
    list(reglas_ajedrez.values()), 
    list(reglas_ajedrez.keys()), 
    default="Sin Categoría"
)


df_limpio['categoria'] = pd.Categorical(
    df_limpio['categoria'], 
    categories=orden_jerarquico, 
    ordered=True
)

In [507]:
df_limpio["categoria"].value_counts()

categoria
Absoluta    555264
Sub 18       53318
Sub 20       50963
Sub 16       49907
Sub 14       39336
Sub 12       24163
Sub 10        8739
Sub 8         1143
Name: count, dtype: int64

### 9.4. Creación de perfil de juego

In [508]:


orden = [
        "completo",
        "especialista_clasico",
        "especialista_rapido",
        "especialista_blitz",
        "clasico_rapido",
        "clasico_blitz",
        "rapido_blitz"]

has_classic = df_limpio["rating"].notna() if "rating" in df_limpio.columns else pd.Series(False, index=df_limpio.index)
has_rapid = df_limpio["rapid_rating"].notna() if "rapid_rating" in df_limpio.columns else pd.Series(False, index=df_limpio.index)
has_blitz = df_limpio["blitz_rating"].notna() if "blitz_rating" in df_limpio.columns else pd.Series(False, index=df_limpio.index)


condiciones_perfil = [
            has_classic & has_rapid & has_blitz,          # completo
            has_classic & ~has_rapid & ~has_blitz,        # especialista_clasico
            ~has_classic & has_rapid & ~has_blitz,        # especialista_rapido
            ~has_classic & ~has_rapid & has_blitz,        # especialista_blitz
            has_classic & has_rapid & ~has_blitz,         # clasico_rapido
            has_classic & ~has_rapid & has_blitz,         # clasico_blitz
            ~has_classic & has_rapid & has_blitz,         # rapido_blitz
        ]

df_limpio["player_profile"] = np.select(
            condiciones_perfil,
            orden,
            default="sin_elo"
        )

df_limpio["player_profile"] = pd.Categorical(
            df_limpio["player_profile"],
            categories=orden,
            ordered=True
        )

In [509]:
df_limpio["player_profile"].value_counts()

player_profile
especialista_clasico    226071
completo                192425
especialista_rapido     137115
clasico_rapido          104843
especialista_blitz       43081
rapido_blitz             41447
clasico_blitz            37851
Name: count, dtype: int64

## 9.5 Correcciones de titulos y genero

In [510]:
df_anomalias = df_limpio[
    (df_limpio["sex"] == "M") & 
    (df_limpio["w_title"].isin(TITLE_WOMAN))
]

df_anomalias

KeyError: 'w_title'

## 10. Segmentación de Jugadores Activos

Creación del subconjunto `df_activos`:
- Excluye flags `'i'` (inactivo) y `'wi'` (mujer inactiva).
- Trunca edad máxima a 95 años (eliminar outliers inverosímiles).

In [ ]:

df_activos = df_limpio[~df_limpio['flag'].isin(['i', 'wi'])].copy()
df_activos = df_activos[df_activos['edad'] <= 95].copy()

df_activos.describe()

            rating  rapid_rating  blitz_rating     birthday       edad
count     220333.0      329153.0      205306.0     441904.0   441904.0
mean   1733.755988    1656.26683   1702.667974  1994.176948  31.823052
std     223.732248    200.343571    215.843855    19.745614  19.745614
min         1400.0        1400.0        1400.0       1931.0        4.0
25%         1555.0        1500.0        1532.0       1980.0       16.0
50%         1699.0        1610.0        1663.0       2002.0       24.0
75%         1872.0        1767.0        1832.0       2010.0       46.0
max         2823.0        2801.0        2860.0       2022.0       95.0

In [ ]:
df_activos.info()

<class 'pandas.DataFrame'>
Index: 441904 entries, 6 to 1933944
Data columns (total 17 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   fideid          441904 non-null  string
 1   name            441904 non-null  string
 2   country         441904 non-null  category
 3   sex             441904 non-null  category
 4   title           441904 non-null  category
 5   w_title         441904 non-null  category
 6   o_title         441904 non-null  category
 7   rating          220333 non-null  Int64
 8   rapid_rating    329153 non-null  Int64
 9   blitz_rating    205306 non-null  Int64
 10  birthday        441904 non-null  Int64
 11  flag            441904 non-null  category
 12  snapshot_date   441904 non-null  object
 13  es_activo       441904 non-null  bool
 14  edad            441904 non-null  Int64
 15  categoria       441904 non-null  category
 16  player_profile  441904 non-null  category
dtypes: Int64(5), bool(1), category(8), object(1), string(2)
memory usage: 47.9+ MB